version: "3"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=localdev
      - POSTGRES_PASSWORD=localdev
    volumes:
      - db_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6
  web:
    build: exegete/
    command: uvicorn
    volumes:
      - ./exegete/:/app:delegated
      - ./data/:/data
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=localdev
      - DB_USERNAME=postgres
      - DB_PASSWORD=localdev
      - DEBUG=1
    depends_on:
      - db
      - redis
volumes:
  db_pgdata:
