version: "3"
services:
  db:
    image: postgres:15
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=localdev
      - POSTGRES_PASSWORD=localdev
    volumes:
      - db_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6
  backend:
    build: backend/
    volumes:
      - ./backend/:/app:delegated
      - ./data/:/data
    ports:
      - "8000:8000"
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
      - PG_DSN=postgresql+psycopg2://postgres:localdev@db:5432/localdev
      - PG_ASYNC_DSN=postgresql+asyncpg://postgres:localdev@db:5432/localdev
      - BASE_URL=http://localhost:3000
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - .env_local
    depends_on:
      - db
      - redis
volumes:
  db_pgdata:
