[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.81.0"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
fastapi-users = {extras = ["sqlalchemy"], version = "^10.1.5"}
pydantic = "^1.10.1"
jsonschema = "^4.15.0"
lxml = "^4.9.1"
aiohttp = "^3.8.1"
alembic = "^1.8.1"
aioredis = "^2.0.1"
nltk = "^3.7"
requests = "^2.28.1"
asyncpg = "^0.26.0"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
