[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.87.0"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^10.2.1"}
pydantic = "^1.10.2"
jsonschema = "^4.17.0"
lxml = "^4.9.1"
aiohttp = "^3.8.3"
alembic = "^1.8.1"
aioredis = "^2.0.1"
nltk = "^3.7"
requests = "^2.28.1"
asyncpg = "^0.27.0"
psycopg2 = "^2.9.5"

[tool.poetry.dev-dependencies]
black = "*"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.281"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
