[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
fastapi-users = {extras = ["sqlalchemy"], version = "^9.3.0"}
psycopg2 = "^2.9.3"
pydantic = "^1.9.0"
jsonschema = "^4.4.0"
lxml = "^4.9.1"
databases = {extras = ["postgresql"], version = "^0.5.5"}
aiohttp = "^3.8.1"
alembic = "^1.7.7"
aioredis = "^2.0.1"
nltk = "^3.7"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
