[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.70.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^8.1.1"}
psycopg2 = "^2.9.1"
pydantic = "^1.8.2"
jsonschema = "^4.1.2"
lxml = "^4.6.3"
databases = {extras = ["postgresql"], version = "^0.5.3"}
aiohttp = "^3.8.0"
alembic = "^1.7.4"
aioredis = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
