[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.89.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^10.3.0"}
pydantic = "^1.10.4"
jsonschema = "^4.17.3"
lxml = "^4.9.2"
aiohttp = "^3.8.3"
alembic = "^1.9.2"
nltk = "^3.8.1"
requests = "^2.28.2"
asyncpg = "^0.27.0"
psycopg2 = "^2.9.5"
redis = "^4.5.3"

[tool.poetry.dev-dependencies]
black = "^22.12.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.283"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
