[tool.poetry]
name = "exegete"
version = "0.1.0"
description = "backend for exegete.app"
authors = ["Grahame Bowland <grahame@oreamnos.com.au>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
fastapi-users = {extras = ["sqlalchemy"], version = "^12.0.0"}
pydantic = "^1.10.11,<2"  # 2.0 breaks fastapi-users at the moment
jsonschema = "^4.18.0"
lxml = "^4.9.3"
aiohttp = "^3.8.4"
alembic = "^1.11.1"
nltk = "^3.8.1"
requests = "^2.31.0"
asyncpg = "^0.28.0"
psycopg2 = "^2.9.6"
redis = "^4.6.0"
watchfiles = "^0.19.0"

[tool.poetry.dev-dependencies]
black = "^23.3.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.283"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
