"""empty message

Revision ID: 1c9ce07d9c84
Revises: fd14d0b796c7
Create Date: 2022-02-12 08:42:08.171483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c9ce07d9c84'
down_revision = 'fd14d0b796c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'workspace', new_column_name='data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'data', new_column_name='workspace')
    # ### end Alembic commands ###
