"""empty message

Revision ID: 1efc929f1ef0
Revises: 9d793cf691c9
Create Date: 2021-11-03 16:23:15.168802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1efc929f1ef0'
down_revision = '9d793cf691c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('workspace', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'workspace')
    # ### end Alembic commands ###
