"""empty message

Revision ID: 2ac3615e99d6
Revises: 1efc929f1ef0
Create Date: 2021-12-31 09:10:48.080503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac3615e99d6'
down_revision = '1efc929f1ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workspace', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'updated')
    op.drop_column('workspace', 'created')
    # ### end Alembic commands ###
