"""empty message

Revision ID: ba023fe267ba
Revises: 1c9ce07d9c84
Create Date: 2025-10-24 00:24:09.133935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba023fe267ba'
down_revision = '1c9ce07d9c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    # ### end Alembic commands ###
