"""empty message

Revision ID: ed0fc129fac8
Revises: 2ac3615e99d6
Create Date: 2022-01-02 16:49:19.300667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0fc129fac8'
down_revision = '2ac3615e99d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
