import React from "react";
import { saveWorkspaceAPI } from "./APIWorkspaceStorage";
import { saveWorkspaceLocal } from "./LocalWorkspaceStorage";
import { DirtyState, IWorkspaceContext, WorkspaceContext, WorkspaceAction } from "./Workspace";
import { diff } from "jsondiffpatch";

export const WorkspaceAutoSave: React.FC = ({ children }) => {
    const { state, dispatch } = React.useContext<IWorkspaceContext>(WorkspaceContext);

    React.useEffect(() => {
        const makeWorkspaceDelta = () => {
            if (!state.workspace || !state.last_workspace) {
                return undefined;
            }
            // calculate and push undo information
            const last = {
                cells: state.last_workspace.data.cells,
                global: state.last_workspace.data.global,
            };
            const now = {
                cells: state.workspace.data.cells,
                global: state.workspace.data.global,
            };
            const delta = diff(now, last);
            if (!delta) {
                return undefined;
            }
            return {
                ...state.workspace,
                data: {
                    ...state.workspace.data,
                    history: {
                        ...state.workspace.data.history,
                        undo: [delta, ...state.workspace.data.history.undo],
                        redo: [],
                    },
                },
            };
        };
        if (state.dirty === DirtyState.CLEAN) {
            return;
        }
        if (!state.workspace || !state.valid) {
            return;
        }
        const timeoutID = window.setTimeout(() => {
            if (!state.workspace || !state.valid || !state.last_workspace) {
                return;
            }
            // detail here: if we calculated a new state for the workspace history, we need it to be
            // set in the current version of the workspace state. if we didn't, then we don't want to
            // clobber the history that might have been generated by the user while the save was in progress
            const workspace = state.dirty === DirtyState.MAKE_DELTA ? makeWorkspaceDelta() : state.workspace;
            if (!workspace) {
                return;
            }
            const dispatch_obj: WorkspaceAction =
                state.dirty === DirtyState.MAKE_DELTA
                    ? { type: "workspace_saved", workspace: workspace, set_history: true }
                    : { type: "workspace_saved", workspace: workspace, set_history: false };
            if (state.local) {
                saveWorkspaceLocal(workspace);
                dispatch(dispatch_obj);
            } else {
                saveWorkspaceAPI(workspace).then(() => {
                    dispatch(dispatch_obj);
                });
            }
        }, 1000);

        return () => {
            window.clearTimeout(timeoutID);
        };
    }, [state.dirty, dispatch, state.local, state.valid, state.workspace, state.last_workspace]);
    return <>{children}</>;
};
