import React from "react";
import { saveWorkspaceAPI } from "./APIWorkspaceStorage";
import { saveWorkspaceLocal } from "./LocalWorkspaceStorage";
import { DirtyState, selectWorkspace, workspaceSaved } from "./Workspace";
import { diff } from "jsondiffpatch";
import { useAppDispatch, useAppSelector } from "../exegete/hooks";

export const WorkspaceAutoSave: React.FC<React.PropsWithChildren<unknown>> = ({ children }) => {
    const state = useAppSelector(selectWorkspace);
    const dispatch = useAppDispatch();

    React.useEffect(() => {
        const makeWorkspaceDelta = () => {
            if (!state.workspace || !state.last_workspace) {
                return undefined;
            }
            // calculate and push undo information
            const last = {
                cells: state.last_workspace.data.cells,
                global: state.last_workspace.data.global,
            };
            const now = {
                cells: state.workspace.data.cells,
                global: state.workspace.data.global,
            };
            const delta = diff(now, last);
            if (!delta) {
                return undefined;
            }
            return {
                ...state.workspace,
                data: {
                    ...state.workspace.data,
                    history: {
                        ...state.workspace.data.history,
                        undo: [delta, ...state.workspace.data.history.undo],
                        redo: [],
                    },
                },
            };
        };
        if (state.dirty === DirtyState.CLEAN) {
            return;
        }
        if (!state.workspace || !state.valid) {
            return;
        }
        const timeoutID = window.setTimeout(() => {
            if (!state.workspace || !state.valid || !state.last_workspace) {
                return;
            }
            // detail here: if we calculated a new state for the workspace history, we need it to be
            // set in the current version of the workspace state. if we didn't, then we don't want to
            // clobber the history that might have been generated by the user while the save was in progress
            const workspace = state.dirty === DirtyState.MAKE_DELTA ? makeWorkspaceDelta() : state.workspace;
            if (!workspace) {
                return;
            }
            const dispatch_fn =
                state.dirty === DirtyState.MAKE_DELTA
                    ? () => {
                          dispatch(workspaceSaved([workspace, true]));
                      }
                    : () => {
                          dispatch(workspaceSaved([workspace, false]));
                      };

            // FIXME? Maybe need a thunk
            if (state.local) {
                saveWorkspaceLocal(workspace);
                dispatch_fn();
            } else {
                saveWorkspaceAPI(workspace).then(() => {
                    dispatch_fn();
                });
            }
        }, 1000);

        return () => {
            window.clearTimeout(timeoutID);
        };
    }, [state.dirty, dispatch, state.local, state.valid, state.workspace, state.last_workspace]);
    return <>{children}</>;
};
